networks:
   mynetwork:
      driver: bridge

services:
   database:
#      platform: linux/amd64
      image: mcr.microsoft.com/mssql/server:latest
      container_name: sql-app-pi6
      volumes:
         - ./.docker/dbdata:/var/lib/sqlserver
      environment:
         SA_PASSWORD: "Root1234@"
         ACCEPT_EULA: "Y"
         MSSQL_PID: "Developer"
      expose:
         - "1433"
      ports:
         - "1433:1433"
      restart: always
      tty: true
      networks:
         - mynetwork
   app:
      image: go-app-pi6:latest
      container_name: go-app-pi6
      build:
         context: ./src
         dockerfile: Dockerfile
      networks:
         - mynetwork
      env_file:
         - ".env"
         - ".env.docker"
      restart: on-failure
      depends_on:
         - database
