version: "3.8"

networks:
  mynetwork:
    driver: bridge

services:
  database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: PI6
    volumes:
      - ./.docker/dbdata:/var/lib/sqlserver
    environment:
      SA_PASSWORD: "Root1234@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${Sa_Password:-password123} -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
    expose:
      - "1433"
    ports:
      - "1433:1433"
    restart: always
    tty: true
    networks:
      - mynetwork
